services:
    backend:
        context: ./backend
        container_name: backend
        build:
            dockerfile: Dockerfile
        ports:
            - "${PORT}:${PORT}"
        environment:
            - POSTGRES_HOST=postgres
            - DB_PORT=${DB_PORT}
            - DB_USER=${DB_USER}
            - DB_PASSWORD=${DB_PASSWORD}
            - DB_NAME=${DB_NAME}
            - DB_URL=${DB_URL}
            - PORT=${PORT}
            - NODE_ENV=${NODE_ENV}
            - ACCESS_SECRET=${ACCESS_SECRET}
            - REFRESH_SECRET=${REFRESH_SECRET}
            - COOKIE_SECRET=${COOKIE_SECRET}
        volumes:
            - ./backend:/srv/node/app/backend
        depends_on:
            - postgres

    postgres:
        container_name: postgres
        image: postgres:15
        ports:
            - "${DB_PORT}:${DB_PORT}"
        environment:
            DB_USER: ${DB_USER}
            DB_PASSWORD: ${DB_PASSWORD}
            DB_NAME: ${DB_NAME}
            DB_URL: ${DB_URL}
        volumes:
            - pgdata:/var/lib/postgresql/data

volumes:
    pgdata:
